### ISSUE TITLE
How to prevent erb files from caching

### ISSUE THREAD

**Issue by sergueif** [sstephenson/sprockets#210]
Hi,

How do I prevent a file from caching? I compile a .js.erb file, and the ruby code in there evaluates differently depending on options passed to the environment.context_class. 

I looked at the caching code in sprockets and it seems that it makes a decision to cache just based on file mtimes, digests, etc. 

foo.js.erb
var foo = <%= Kernel.rand %>

or

<% if options[:mock_ajax] %>
//= require mock_ajax
<% end %>

How  do I prevent certain files from caching?

**Comment by jeremyhaile** [comment]
I'm having this problem as well. I have some JS code that needs to reference assets, and I use asset digests.

So I generate a JS object in one file using erb that has the mapping from logical name to the digest asset names. Since digests change every time I deploy, I want this ONE file to be recompiled every time I deploy. I don't want ALL files to be recompiled (as would happen if I incremented the assets.version)

I'd really like some way to tell sprockets that I want it to recompile a single file on every deploy as mentioned in #486

**Comment by hammady** [comment]
The solution is here #563.
