### ISSUE TITLE
Confusion around depend_on_asset

### ISSUE THREAD

**Issue by sb8244** [sstephenson/sprockets#698]
I'm a bit confused by the behavior of depend_on_asset and have sunk some time into looking at the behavior.

Basically, is it possible to say `//= depend_on_asset a_folder` and have all files under that folder be depended on? I currently can say `a_folder/index.html.slim` but get FileNotFound when I do `a_folder`

**Comment by josh** [comment]
`depend_on_asset` has to receive an asset not a directory.

Just curious what you're using it for? Its more likely you shouldn't actually be using it.

**Comment by sb8244** [comment]
I have a directory of slim templates that I am placing into the Angular $templateCache using sprockets:

```ruby
angular.module('templates', []).
  run(['$templateCache', function($templateCache) {
  <%
    environment.context_class.instance_eval { include ActionView::Helpers::JavaScriptHelper }
    app_root  = File.expand_path('../../../', __FILE__)
    templates = File.join(app_root, %w{templates ** *.slim})

    Dir.glob(templates).sort.each do |f|

      depend_on(f)
      key = f.gsub(%r(^#{app_root}/templates/),'').gsub(/.slim$/, "")
      content = environment.find_asset(f).body
  %>
  $templateCache.put("<%= key %>", "<%= escape_javascript(content) %>");
  <% end %>
}]);
```

This works great, and the depend_on ensures that file changes cause this script to bust cache. However, when I add a new file, it doesn't bust the cache because the asset isn't depended on.

It would be possible to list all files in many `depend_on`s but that is cumbersome with 100+ templates that could change

**Comment by josh** [comment]
In your dir glob, I'd add a `depend_on` for each of the directories you reading from. Just call it from ruby/erb, don't bother with the comment directive support.

The script looks okay, maybe some other tips

* You shouldn't have to pull in `JavaScriptHelper` everytime. It should exist by default, otherwise, just do it once on initialize instead of on every template eval
* `environment.root` should be your app root
* Instead of the gsub for format the key, just try `asset.logical_path`

**Comment by sb8244** [comment]
Thanks Josh.
